# Generated by Django 6.0.4 on 2026-04-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('fan', models.CharField(choices=[('matematika', 'Matematika'), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix'), ('geografiya', 'Geografiya'), ('adabiyot', 'Adabiyot'), ('ona_tili', 'Ona tili'), ('ingliz_tili', 'Ingliz tili'), ('informatika', 'Informatika'), ('chizmachilik', 'Chizmachilik'), ('jismoniy', 'Jismoniy tarbiya')], max_length=50)),
                ('holat', models.CharField(choices=[('keldi', 'Keldi'), ('kelmadi', 'Kelmadi'), ('kech_keldi', 'Kech keldi'), ('sababli', 'Sababli')], max_length=20)),
                ('baho', models.IntegerField(blank=True, null=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Musobaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('fan', models.CharField(choices=[('matematika', 'Matematika'), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix'), ('geografiya', 'Geografiya'), ('adabiyot', 'Adabiyot'), ('ona_tili', 'Ona tili'), ('ingliz_tili', 'Ingliz tili'), ('informatika', 'Informatika'), ('chizmachilik', 'Chizmachilik'), ('jismoniy', 'Jismoniy tarbiya')], max_length=50)),
                ('tavsif', models.TextField()),
                ('boshlanish', models.DateField()),
                ('tugash', models.DateField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='musobaqalar/')),
                ('ishtirokchilar', models.ManyToManyField(blank=True, related_name='musobaqalar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('reyting', models.FloatField(default=0.0)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('tasdiqlangan', models.BooleanField(default=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reyting', '-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='TestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(choices=[('matematika', 'Matematika'), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix'), ('geografiya', 'Geografiya'), ('adabiyot', 'Adabiyot'), ('ona_tili', 'Ona tili'), ('ingliz_tili', 'Ingliz tili'), ('informatika', 'Informatika'), ('chizmachilik', 'Chizmachilik'), ('jismoniy', 'Jismoniy tarbiya')], max_length=50)),
                ('mavzu', models.CharField(max_length=200)),
                ('ball', models.IntegerField()),
                ('max_ball', models.IntegerField(default=10)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_natijalari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XulqBaho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('fikr', models.TextField()),
                ('ball', models.IntegerField(default=5)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('baho_beruvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bergan_baholar', to=settings.AUTH_USER_MODEL)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xulq_baholar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
